### ISSUE TITLE
Dart SDK 2.2.0 is not supported in Flutter stable

### ISSUE THREAD

**Issue by robsonfingo** [tekartik/idb_shim.dart#2]
Can you please not require the latest version of the Dart SDK until Flutter catches up. We'd like to use this library in a Flutter project. Thanks!

**Comment by alextekartik** [comment]
Sorry, I went too fast on the new Set() declaration. I encountered the same issue and this package has to remain compatible with flutter stable. This should be fixed in the 1.7.2+1 version just published

**Comment by robsonfingo** [comment]
Thank you!
