### ISSUE TITLE
query for getAll method

### ISSUE THREAD

**Issue by sb996** [tekartik/idb_shim.dart#22]
how do I can get records from my table by where clause in query with getAll method?
please show me with example.

**Comment by alextekartik** [comment]
Indexed DB supports very basic queries:

https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/getAll

There is no such where clause, you can either provide a key or a key range and you can filter the results afterwards. idb_shim does not add any specific behavior here.

For exampe you can do something like:

```dart
await objectStore.getAll(KeyRange.bound(2, 3))
```

To get records with id 2 and 3 (if they exists).

**Comment by soroorbateni** [comment]
> Indexed DB supports very basic queries:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/getAll
> 
> There is no such where clause, you can either provide a key or a key range and you can filter the results afterwards. idb_shim does not add any specific behavior here.
> 
> For exampe you can do something like:
> 
> ```dart
> await objectStore.getAll(KeyRange.bound(2, 3))
> ```
> 
> To get records with id 2 and 3 (if they exists).


thanks for your response
So if I want to search by another field like name there is no way?
I have to check this myself?

**Comment by alextekartik** [comment]
> So if I want to search by another field like name there is no way?

You can create index but here as well you are limited to key or keyrange. Advanced where clause have to be done in memory.
