### ISSUE TITLE
get indexed db data fail

### ISSUE THREAD

**Issue by AsteriskZuo** [tekartik/idb_shim.dart#23]
error tip: `Bad state: Stream has already been listened to.`

env: 
```
xxx@administratordeMac-mini-2 dart % flutter --version
Flutter 1.26.0-17.6.pre • channel beta • https://gitee.com/mirrors/Flutter.git
Framework • revision a29104a69b (3 days ago) • 2021-02-16 09:26:56 -0800
Engine • revision 21fa8bb99e
Tools • Dart 2.12.0 (build 2.12.0-259.12.beta)
```

System Software Overview:
```
  System Version:	macOS 10.15.7 (19H2)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	administrator的Mac mini
  User Name:	zuoyu (zuoyu)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	1:30
```

project pubspec.yaml
```
dependencies:
  idb_shim: ^1.12.2+2
  ...
```

Code snippet:
```
import 'package:idb_shim/idb.dart';
import 'package:idb_shim/idb_browser.dart';
...
class StorageImpl implements Storage {
 IdbFactory _idbFactory;
  Database _db;
  ...
  StorageImpl([this._version = 1]) : super() {
    IMLog.infoPrint('$TAG');
    _idbFactory = getIdbFactory();
  }
  ...
    Transaction getTransaction(String storeName, [String mode = 'readwrite']) {
    return _db.transaction(storeName, mode);
  }

  Future commit(Transaction transaction) async {
    return await transaction.completed;
  }
  void upgradeTable(VersionChangeEvent event, int currentVersion) {
    if (currentVersion < 1) {
      var messageObjectStore =
          event.database.createObjectStore('message', autoIncrement: true);
      messageObjectStore.createIndex('msg_id', 'msg_id', unique: true);
      messageObjectStore.createIndex('conv_id', 'conv_id');
      messageObjectStore.createIndex('conv_type', 'conv_type');
      messageObjectStore.createIndex('sender_id', 'sender_id');
      messageObjectStore.createIndex('direction', 'direction');
      messageObjectStore.createIndex('timestamp', 'timestamp');
      messageObjectStore.createIndex('send_timestamp', 'send_timestamp');
      messageObjectStore.createIndex('msg_type_str', 'msg_type_str');
      messageObjectStore.createIndex('msg_body', 'msg_body');
      messageObjectStore.createIndex('msg_status', 'msg_status');
      messageObjectStore.createIndex('msg_read', 'msg_read');
      messageObjectStore.createIndex('msg_revoked', 'msg_revoked');
      messageObjectStore.createIndex('logical_deleted', 'logical_deleted');
      messageObjectStore.createIndex('cus_int', 'cus_int');
      messageObjectStore.createIndex('cus_data', 'cus_data');
      messageObjectStore.createIndex('msg_push', 'msg_push');

      var kvObjectStore =
          event.database.createObjectStore('kv', autoIncrement: true);
      kvObjectStore.createIndex('key', 'key', unique: true);
      kvObjectStore.createIndex('value', 'value');
      kvObjectStore.createIndex('value_type', 'value');
      kvObjectStore.createIndex('remark', 'value');
    } else if (currentVersion < 2) {
      var messageObjectStore = event.transaction.objectStore('message');
      messageObjectStore.createIndex('convAndType', ['conv_id', 'conv_type']);
      messageObjectStore.createIndex(
          'convAndTypeAndTimestamp', ['conv_id', 'conv_type', 'timestamp']);
    } else if (currentVersion < 3) {
    } else {}
  }
  @override
  Future open(String root, String appKey, String uid) async {
    IMLog.infoPrint('$TAG open: $root: $appKey: $uid');
    _root = root;
    _appKey = appKey;
    _uid = uid;
    try {
      _db = await _idbFactory.open('${_appKey}_${_uid}', version: _version,
          onUpgradeNeeded: (VersionChangeEvent event) {
        var db = event.database;
        var currentVersion = event.oldVersion;
        while (currentVersion <= event.newVersion) {
          upgradeTable(event, currentVersion);
          ++currentVersion;
        }
      });
    } catch (e) {
      IMLog.errorPrint('$TAG open: error: $e');
    }
  }
  @override
  Future<List> getLocalConversationList() async {
    IMLog.infoPrint('$TAG getLocalConversationList:');
    var localConversationList = <String, DBConversation>{};
    var localConversationReadTimestampList = <String, int>{};
    var localConversationLastInBoxTimestampList = <String, int>{};
    var inboxTimestamp = 0;
    var outBoxTimestamp = 0;
    final cursor = getTransaction('message', 'readonly')
        .objectStore('message')
        .index('timestamp')
        .openCursor(
            range: KeyRange.bound(0, JavascriptNumber.infinity),
            direction: 'prev',
            autoAdvance: false);
    var count = 0;
    final maxCount = 10000;
    var ret = Completer<List>();
    StreamSubscription streamSubscription;
    cursor.listen((CursorWithValue cwv) {
      var value = cwv.value as Map<String, dynamic>;
      ret.complete([]);
      ...
    }, onDone: () {
      ret.complete([]);
    }, onError: (error) {
      ret.completeError(error);
    });

    await ret.future;
    ...
  }

}
```

op:
`1. open db and create table is ok`
`2. get db data throw exception: Bad state: Stream has already been listened to.`
`3. location : ...cursor.listen((CursorWithValue cwv)...`

stack info:
```
errors.dart:187 Uncaught (in promise) Error: Bad state: Stream has already been listened to.
    at Object.throw_ [as throw] (errors.dart:236)
    at _SyncStreamController.new.[_subscribe] (stream_controller.dart:635)
    at _ControllerStream.new.[_createSubscription] (stream_controller.dart:786)
    at _ControllerStream.new.listen (stream_impl.dart:473)
    at storage_web.StorageImpl.new.getLastConversationMessageOne (storage_web.dart:296)
    at getLastConversationMessageOne.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at storage_web.StorageImpl.new.getLastConversationMessageOne (storage_web.dart:277)
    at storage_web.StorageImpl.new.getLastConversationMessage (storage_web.dart:555)
    at getLastConversationMessage.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at storage_web.StorageImpl.new.getLastConversationMessage (storage_web.dart:545)
    at cl_im_base.IMApi.__.getLocalMessages (cl_im_api.dart:408)
    at getLocalMessages.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at cl_im_base.IMApi.__.getLocalMessages (cl_im_api.dart:403)
    at chat_page.ChatScreenState.new._loadMessage (chat_page.dart:78)
    at _loadMessage.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at chat_page.ChatScreenState.new.[_loadMessage] (chat_page.dart:76)
    at chat_page.ChatScreenState.new.initState (chat_page.dart:64)
    at framework.StatefulElement.new.[_firstBuild] (framework.dart:4632)
```

thanks.

attach file:

[storage_web.txt](https://github.com/tekartik/idb_shim.dart/files/6009436/storage_web.txt)

**Comment by alextekartik** [comment]
Thanks for the report. Indeed that's puzzling. In getLastConversationMessageOne (where it crashes here), the only think weird I see is that you are completing a completer multiple times, which could cause a crash even during the stream handler and that could cause weird behavior (although it seems unrelated here).  You might try to add first (pseudo code not tested):
```dart
if (!ret.isCompleted) {
  ret.complete(null);
}
```

**Comment by AsteriskZuo** [comment]
I have tried your suggestion, but the above problems still occur.

**Comment by AsteriskZuo** [comment]
In the source code of the library, I discovered something new.
```
class CursorWithValueControllerNative {
  // Sync must be true
  final _ctlr = StreamController<CursorWithValue>(sync: true);

  CursorWithValueControllerNative(Stream<idb.CursorWithValue> stream) {
    stream.listen((idb.CursorWithValue cwv) {
      // idbDevPrint("adding ${cwv.key} ${cwv.value} ${cwv.primaryKey}");
      _ctlr.add(_NativeCursorWithValue(cwv));
    }, onDone: () {
      _ctlr.close();
    }, onError: (error) {
      _ctlr.addError(error);
    });
  }

  Stream<CursorWithValue> get stream => _ctlr.stream;
}
```

This class CursorWithValueControllerNative had use stream listen function, is that what caused it?
library openCursor use stream listen first time, I code use stream listen second time.

**Comment by AsteriskZuo** [comment]
I really want to find something. Debugging a Dart version of a Web-side App causes the Stream to behave abnormally. The above problem does not occur in the non-debug state. I don't know if I'm right, there's no direct evidence.

**Comment by alextekartik** [comment]
Thanks for digging too. I took a deeper look to. Indeed that's puzzling. I have slightly change the native stream implementation to handle listen in a lazy (correct way). Can you try with 1.12.2+3 just published?
Otherwise in general:
- I wait for the transaction to complete before triggering a new one as much as possible
- In a cursor listener, do as a little as possible (event print sometimes work weird here), typically I save the cursor value in a variable and I wait for the transaction to complete to read it. I could be wrong here but even the dart2js implementation is weird (and it was missing the index.openKeyCursor that I had to implement). Any crash here could lead to weird result reported later. And no you cannot debug listeners, I typically just print here for debugging...
- You should also cancel the stream subscription (cursor.listen returns a subscription that should be retained) when done, or just do `await cursor.listen(...).first` if you just need the first item.

indexed_db API is not dart friendly at all...even casting a value as Map<String, dynamic> like you do could crash, you'd better use `(value as Map).cast<String, dynamic>()` instead of `value as Map<String, dynamic>`

**Comment by AsteriskZuo** [comment]
First of all, thank you very much for your patience and guidance. I am a novice who has not been exposed to the dart language for a long time and has only been exposed to the web for a week. Secondly, I also found that there are many flaws in the web version of dart. For example, the stream monitoring you mentioned is best not to breakpoint debugging. I think other asynchronous methods are best not to breakpoint debugging, which is prone to various problems. This is not a problem with your library itself. Also, the web version of dart starts very slowly in the Chrome browser, downloading the required web resources is very time-consuming, and there is a very high probability that the resource loading timeout occurs. Maybe my network also has some problems.

**Comment by alextekartik** [comment]
No problem. As a side note, I use idb_shim in unit test in memory or io to test all my database logic (idb_shim can work on io/flutter too without any browser context). Also I develop mainly on Android or Linux and only test on the web from time to time as, as you mentioned, it is a lot slower.

**Comment by AsteriskZuo** [comment]
First of all, thank you very much for your patient answer and guidance, I am a new to the dart language not long, and contact with the web also a week. Second, I also found that dart has many flaws in the web version. For example, you're talking about a stream monitoring problem that's best not to break point debugging. I think other asynchronous methods are best not to break point debugging, easy to appear a variety of problems. This is not a problem with your library itself. Also, dart's web version starts very slowly in chrome browsers, and downloading the required web resources is time-consuming, with a very high probability of a resource load timeout. Maybe there are some problems with my network.
