### ISSUE TITLE
Nested keypath does not work (with sembast backing)

### ISSUE THREAD

**Issue by peter-fingo** [tekartik/idb_shim.dart#3]
I have only tested this with sembast backing; if keypath is specified as 'foo.bar', then the objectstore will look for a field named 'foo.bar' inside the object, rather than field 'bar' inside the object for field 'foo'. Either I am misunderstanding how indexeddb keypath works, or this is a bug.

**Comment by alextekartik** [comment]
Thanks for the report. It is indeed a bug. Sembast treat foo.bar as 2 distincts parts as you noted. Not sure how this can easily be fixed yet as this could need a workaround in sembast

**Comment by alextekartik** [comment]
Thanks much for the report as I noticed I did not have any test with dot in keyPath. Actually sembast has all the support for it, it was just not well plugged. This should be fixed in 1.7.3, just published

**Comment by peter-fingo** [comment]
Thanks!
