### ISSUE TITLE
Notepad app not available

### ISSUE THREAD

**Issue by ricardoboss** [tekartik/idb_shim.dart#40]
The example app (simple notepad app) you linked to in your README  on pub.dev is no longer available (links to https://github.com/alextekartik/flutter_app_example/tree/master/notepad). You should publish an update soon.

**Comment by alextekartik** [comment]
Sorry the location moved indeed:
https://github.com/alextekartik/flutter_app_example/tree/master/notepad_idb

will fix in the README.md thanks
