### ISSUE TITLE
Enable offline persistence

### ISSUE THREAD

**Issue by mikes222** [tekartik/idb_shim.dart#46]
Is there a way to persist the data in the chrome brower even if the app is closed and restarted? 

I store data with ``store.put(UInt8List object, String key)`` and read them afterwards. However if I stop the app and open it again in the chrome browser from Android Studio the ``onUpgradeNeeded`` callback is executed and the ``objectStoreNames`` do not contain the data anymore so ``createObjectStore()`` is called and reinitializes everything again.

**Comment by alextekartik** [comment]
Sorry I somehow did not see this issue. Data should be persistent as long as the url does not change (i.e. 2 ip addresses will have a different database). Android seems to use a different port every time so you might have to fix the web port used using something like `--web-port 8081` in the Android studio run configuration (`additional run args`)
