### ISSUE TITLE
'Put' does not update objects with the same key as 'Add'

### ISSUE THREAD

**Issue by GruppeGAM** [tekartik/idb_shim.dart#60]
I have the follow test setup:

`
void main() {
    group('IDBShim', () {

    var idbFactory = idbFactoryMemory;

    const keyPath = 'my_key';
    const dbName = 'indexeddb';
    const testStoreName = 'test_store';
    late Database db;

    Transaction? transaction;
    late ObjectStore objectStore;

    void dbCreateTransaction() {
      transaction = db.transaction(testStoreName, idbModeReadWrite);
      objectStore = transaction!.objectStore(testStoreName);
    }
    Future setupDeleteDb() async {
      await idbFactory.deleteDatabase(dbName);
    }
    Future dbSetUp() async {
      await setupDeleteDb();
      void onUpgradeNeeded(VersionChangeEvent e) {
        final db = e.database;
        db.createObjectStore(
          testStoreName,
          keyPath: keyPath,
          autoIncrement: true,
        );
      }
      db = await idbFactory.open(
        dbName,
        version: 1,
        onUpgradeNeeded: onUpgradeNeeded,
      );
    }
    tearDown(() async {
      db.close();
    });
    group('put', () {
      test('should update the object if the secound put has the same id',
          () async {
        await dbSetUp();
        dbCreateTransaction();
        final value = {'test': 'test_value'};
        var id = await objectStore.put(value);
        final value2 = {'test2': 'test_value2'};
        id = await objectStore.put(value2, id);
        expect(id, 1);
        expect(((await sdbExportDatabase(db))['stores'] as List)[1], {
          'name': testStoreName,
          'keys': [1],
          'values': [
            {'test2': 'test_value2', keyPath: 1},
          ]
        });
      });
    });
  });
}`

When I start the test, the following error is thrown:

`Invalid argument(s): The object store uses in-line keys and the key parameter '1' was provided
package:idb_shim/src/sembast/sembast_object_store.dart 69:9    ObjectStoreSembast.getKeyImpl
package:idb_shim/src/sembast/sembast_object_store.dart 367:22  ObjectStoreSembast.put.<fn>
dart:async                                                     new Future.sync
package:idb_shim/src/sembast/sembast_transaction.dart 101:21   TransactionSembast._execute
package:idb_shim/src/sembast/sembast_transaction.dart 126:14   TransactionSembast._next
package:idb_shim/src/sembast/sembast_transaction.dart 127:16   TransactionSembast._next.<fn>
===== asynchronous gap ===========================
dart:async                                                     new Future.sync
package:idb_shim/src/sembast/sembast_transaction.dart 101:21   TransactionSembast._execute
package:idb_shim/src/sembast/sembast_transaction.dart 126:14   TransactionSembast._next
package:idb_shim/src/sembast/sembast_transaction.dart 127:16   TransactionSembast._next.<fn>
===== asynchronous gap ===========================
dart:async                                                     Future.then
package:idb_shim/src/sembast/sembast_transaction.dart 126:33   TransactionSembast._next
package:idb_shim/src/sembast/sembast_transaction.dart 190:30   TransactionSembast.execute.sdbAction.<fn>
package:sembast/src/database_impl.dart 1223:59                 SembastDatabase.transaction.<fn>.<fn>
dart:async                                                     new Future.sync
package:sembast/src/database_impl.dart 1223:32                 SembastDatabase.transaction.<fn>
package:synchronized/src/basic_lock.dart 31:24                 BasicLock.synchronized
package:sembast/src/database_impl.dart 1204:38                 SembastDatabase.transaction
package:idb_shim/src/sembast/sembast_transaction.dart 186:28   TransactionSembast.execute.sdbAction
dart:async                                                     new Future.sync
package:idb_shim/src/sembast/sembast_transaction.dart 219:33   TransactionSembast.execute
package:idb_shim/src/sembast/sembast_object_store.dart 59:25   ObjectStoreSembast.inTransaction
package:idb_shim/src/sembast/sembast_object_store.dart 54:12   ObjectStoreSembast._inWritableTransaction
package:idb_shim/src/sembast/sembast_object_store.dart 366:12  ObjectStoreSembast.put
test/third_party/idb_shim/idb_shim_test.dart 140:36            main.<fn>.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                     _CustomZone.registerUnaryCallback
test/third_party/idb_shim/idb_shim_test.dart 137:9             main.<fn>.<fn>.<fn>`

Shouldn't 'put' update the object, or am I mistaken, or have I misunderstood something?

Thank you in advance

**Comment by GruppeGAM** [comment]
When I run the same test in my web integration test environment, it passes successfully

**Comment by alextekartik** [comment]
Thanks for the report. Indeed the io simulation tries to mimic native behavior. 

> When I run the same test in my web integration test environment, it passes successfully

Great if I could see your code to reproduce as after investigation and test behavior is normal. Indeed you should not pass a key when using keyPath. Instead you should properly fill the keyPath member. Below is a pure indexeddb test that should an error using a code similar to yours and the proper usage below:

```dart
@TestOn('browser')
library;

import 'dart:html';
import 'dart:indexed_db';

import 'package:test/test.dart';

void main() {
  var idbFactory = window.indexedDB!;

  const keyPath = 'my_key';
  var dbName = 'issue60.db';
  const testStoreName = 'test_store';
  late Database db;
  Transaction? transaction;
  late ObjectStore objectStore;

  void dbCreateTransaction() {
    transaction = db.transaction(testStoreName, 'readwrite');
    objectStore = transaction!.objectStore(testStoreName);
  }

  tearDown(() async {
    if (transaction != null) {
      await transaction!.completed;
      transaction = null;
    }
    db.close();
  });

  Future<Database> dbSetUp() async {
    await idbFactory.deleteDatabase(dbName);

    db = await idbFactory.open(dbName, version: 1,
        onUpgradeNeeded: (VersionChangeEvent change) {
      var db = change.target.result as Database;
      db.createObjectStore(testStoreName,
          keyPath: keyPath, autoIncrement: true);
    });
    return db;
  }

  test('put_with_key_error', () async {
    await dbSetUp();
    dbCreateTransaction();
    final value = {'test': 'test_value'};
    var id = await objectStore.put(value);
    expect(
        await objectStore.getObject(id), {'test': 'test_value', 'my_key': id});
    final value2 = {'test2': 'test_value2'};
    try {
      // Bad usage, don't provide the key
      await objectStore.put(value2, id);
      fail('should fail');
    } catch (e) {
      // This prints on Chrome
      // DataError: Failed to execute 'put' on 'IDBObjectStore': The object store uses in-line keys and the key parameter was provided.
      print(e);
      expect(e is TestFailure, isFalse);
      transaction = null;
    }
  });

  test('put_ok', () async {
    await dbSetUp();
    dbCreateTransaction();
    final value = {'test': 'test_value'};
    var id = await objectStore.put(value);
    expect(
        await objectStore.getObject(id), {'test': 'test_value', 'my_key': id});
    final value2 = {'test2': 'test_value2', 'my_key': id};
    // Correct usage, don't provide the key
    await objectStore.put(value2);
    expect(await objectStore.getObject(id),
        {'test2': 'test_value2', 'my_key': id});
  });
}
```

Also as stated in the doc here https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/put
```
DataError DOMException
Thrown if any of the following conditions apply:
* The object store uses in-line keys or has a key generator, and a key parameter was provided.
```

**Comment by alextekartik** [comment]
I don't know if you use keyPath on purpose but if you remove it in your createObjectStore code, it should work.

**Comment by GruppeGAM** [comment]
> When I run the same test in my web integration test environment, it passes successfully

This test is the same, only with in a different directory (./intergration_test/...) and add the following line for the integration testing to the test:
`IntegrationTestWidgetsFlutterBinding.ensureInitialized();`

I run it with the following command line:
`flutter drive --driver=test_driver/integration_test.dart --target=integration_test/web/third_party/idb_shim/idb_shim_test.dart -d web-server --browser-name chrome`

**Comment by GruppeGAM** [comment]
> I don't know if you use keyPath on purpose but if you remove it in your createObjectStore code, it should work.

Thank you for your advice. I wasn't aware of that. Removing the keyPath from the createObjectStore code have resolved the issue. Thank you again!
