### ISSUE TITLE
[Question] is `idb_shim` good to store file of ~3MB on flutter web?

### ISSUE THREAD

**Issue by mariopepe** [tekartik/idb_shim.dart#62]
Hey great piece of work, my congrats.
Sorry for opening an issues, just wanted to ask a question that hopefully will be useful for others too.

Is it possible to use this package to store multiple (50 ish) files of 2/3MB each in Flutter web?

Thanks a lot!
Best

**Comment by alextekartik** [comment]
Hello by files I think you mean databases? (well you're right it might end up being a file somewhere).

The limitation here is the IndexedDB limitation on the browser you use.

I think, Firefox/Chrome allows 2GB data to be stored by each origin and Safari allows 1GB per origin. so it should be good. Don't take this information for granted, I found it in StackOverflow...

**Comment by mariopepe** [comment]
No sorry for my mistake, I need to store`.mp3` files.

Of course I could store as `Uint8List` not sure if this is the best way tho.

To be clear I cache certain files in the mobile (iOS and Android) version of my flutter app and Id like to do the same for the web version.

And i thaught this could be a good solution?

Or maybe I am saying something totally stupid 😅 In that case sorry!

**Comment by alextekartik** [comment]
For files, I recommend you take a look at [fs_shim](https://pub.dev/packages/fs_shim) which is built on top of idb shim on the web. With the same API you can save/read files on iOS/Android and Web ! Big files are split in multiple indexed db records on the web. Documentation is poor sorry but the API mimic the File io API without the synchronous API (on the web the API has to be asynchronous)

**Comment by mariopepe** [comment]
Thanks so much for your kind replay! I'll definitely use it!! Congrats again!
