### ISSUE TITLE
Stream data from indexedDB

### ISSUE THREAD

**Issue by jaxnz** [tekartik/idb_shim.dart#63]
Hi,

Is it possible to listen to database changes? Aka stream data from the database?

**Comment by alextekartik** [comment]
Unfortunately there is no such think in the indexedDB specs so it has to be implemented at the application level. For single page/app (web or io) it is simple as you can for example simply track any change on a given store. For multiple tabs (web) it is more complex, one solution being using a local storage notification between tabs. That is for example what sembast_web use (on top of idb_shim) to synchronize data between multiple tabs.
