### ISSUE TITLE
Not Compatible with Flutter 3.22.0 wasm

### ISSUE THREAD

**Issue by ARASHz4** [tekartik/idb_shim.dart#64]
Not Compatible with Flutter 3.22.0 wasm

**Comment by alextekartik** [comment]
Have you tried the latest version (2.4.1+1) ?
I was able to build a wasm version on this example (counter app with indexeddb):
https://github.com/alextekartik/flutter_app_example/tree/master/demo_idb

Can you tell me what error you seeing?
